plugins {
    id 'java'
    id 'java-library'
}

base {
    archivesName = "kibu-schematic-api"
}

moduleDependencies(project, [
        'kibu-nbt-api'
])

publishing {
    publications {
        named("mavenJava", MavenPublication) {
            pom {
                name = 'kibu-schematic-api'
                description = 'Platform independent schematic API.'
            }
        }
    }
}

test {
    useJUnitPlatform()
}