plugins {
    id 'java'
    id 'java-library'
}

base {
    archivesName = "kibu-schematic-api"
}

moduleDependencies(project, [
        'kibu-nbt-api'
])

publishing {
    publications {
        named("mavenJava", MavenPublication) {
            pom {
                name = 'kibu-schematic-api'
                description = 'Platform independent schematic API.'
            }
        }
    }
}

dependencies {
    testCompileOnly 'org.jetbrains:annotations:24.1.0'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
}

test {
    useJUnitPlatform()
}