plugins {
    id 'java'
    id 'java-library'
}

base {
    archivesName = "kibu-config-api"
}

publishing {
    publications {
        named("mavenJava", MavenPublication) {
            pom {
                name = 'kibu-config-api'
                description = 'Platform independent configuration API.'
            }
        }
    }
}

dependencies {
    implementation(libs.night.config.core)
    implementation(libs.night.config.toml)
}

test {
    useJUnitPlatform()
}