plugins {
    id 'java'
    id 'java-library'
}

base {
    archivesName = "kibu-config-api"
}

publishing {
    publications {
        named("mavenJava", MavenPublication) {
            pom {
                name = 'kibu-config-api'
                description = 'Platform independent configuration API.'
            }
        }
    }
}

dependencies {
    implementation('com.electronwill.night-config:core:3.8.1')
    implementation('com.electronwill.night-config:toml:3.8.1')
}

test {
    useJUnitPlatform()
}