plugins {
    id 'java'
    id 'java-library'
}

archivesBaseName = "kibu-config-api"

publishing {
    publications {
        mavenJava(MavenPublication) {
            pom {
                name = 'kibu-config-api'
                description = 'Platform independent configuration API.'
            }
        }
    }
}

dependencies {
    implementation('com.electronwill.night-config:core:3.8.1')
    implementation('com.electronwill.night-config:toml:3.8.1')

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
}

test {
    useJUnitPlatform()
}