plugins {
    id 'java'
}

base {
    archivesName = "kibu-map-api"
}

moduleDependencies(project, [
        'kibu-hook-api'
])

publishing {
    publications {
        named("mavenJava", MavenPublication) {
            pom {
                name = 'kibu-map-api'
                description = 'API for interacting with filled map items.'
            }
        }
    }
}

test {
    useJUnitPlatform()
}