plugins {
    alias(libs.plugins.fabric.loom) apply false
    alias(libs.plugins.maven.publish)
    alias(libs.plugins.gradle.build.utils)
}

Properties props = buildUtils.loadProperties('publish.properties')

ext {
    versionPattern = "^[0-9]+\\.[0-9]+\\.[0-9]+(?:[-+][a-zA-Z0-9.]+)?\$"
}

version = "${project.mod_version}+${libs.versions.minecraft.get()}"

def modId = project.mod_id

allprojects {
    group = project.maven_group

    apply plugin: 'java'
    apply plugin: 'maven-publish'

    def initFile = file('init.gradle')

    ext {
        isMc = true
    }

    if (initFile.exists()) {
        apply from: initFile
    }

    if (ext.isMc) {
        apply plugin: 'net.fabricmc.fabric-loom'
    }

    repositories {
        mavenCentral()

        maven {
            url "https://repo.lclpnet.work/repository/internal"
        }
    }

    dependencies {
        compileOnly(libs.jetbrains.annotations)
        testCompileOnly(libs.jetbrains.annotations)

        testImplementation(libs.junit.jupiter.params)
        testImplementation(libs.mockito.core)
    }

    if (ext.isMc) {
        dependencies {
            minecraft(libs.minecraft)
            implementation(libs.fabric.loader)
            implementation(libs.fabric.api)

            testImplementation(libs.fabric.loader.junit)
        }
    } else {
        dependencies {
            testImplementation(libs.junit.jupiter.api)
            testRuntimeOnly(libs.junit.jupiter.engine)
            testRuntimeOnly(libs.junit.platform.launcher)
        }
    }

    test {
        useJUnitPlatform()
    }

    processResources {
        inputs.property "version", project.version
        inputs.property "loader_version", libs.versions.fabric.loader.get()
        inputs.property "minecraft_compat", project.minecraft_compat

        filesMatching("fabric.mod.json") {
            expand "version": project.version,
                    "loader_version": libs.versions.fabric.loader.get(),
                    "minecraft_compat": project.minecraft_compat
        }
    }

    tasks.withType(JavaCompile).configureEach {
        it.options.release = 25
    }

    java {
        withSourcesJar()

        sourceCompatibility = JavaVersion.VERSION_25
        targetCompatibility = JavaVersion.VERSION_25
    }

    [jar, sourcesJar].each {
        it.from(rootProject.file('LICENSE')) {
            rename { "${it}_${project.base.archivesName.get()}"}
        }
    }

    publishing {
        buildUtils.setupPublishRepository(repositories, props)
    }
}

subprojects {
    version = getSubprojectVersion(project)

    if (!ext.isMc) {
        configureNonLoomProject(project)
    }

    publishing {
        publications {
            create("mavenJava", MavenPublication) {
                artifactId = project.base.archivesName.get()

                from components.java
            }
        }
    }

    publishMavenJavaPublicationToMavenRepository.onlyIf {
        return !checkProjectIsDeployed(project, props)
    }

    afterEvaluate {
        tasks.find { (it.name == "genSources") }?.setEnabled(false)
        tasks.find { (it.name == "genSourcesWithCfr") }?.setEnabled(false)
        tasks.find { (it.name == "genSourcesWithFernFlower") }?.setEnabled(false)
        tasks.find { (it.name == "genSourcesWithVineflower") }?.setEnabled(false)
    }
}

base {
    archivesName.set(modId)
}

import groovy.xml.XmlSlurper
import work.lclpnet.build.task.GithubDeploymentTask

def env = System.getenv()

tasks.register("github", GithubDeploymentTask) {
    dependsOn tasks.jar

    config {
        token = env.get("GITHUB_TOKEN")
        repository = env.get("GITHUB_REPOSITORY")
    }

    release {
        title = "[${libs.versions.minecraft.get()}] Kibu $project.version"
        tag = project.version
    }

    assets.add(tasks.jar.archiveFile.get())
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.base.archivesName.get()

            from components.java

            pom {
                name = 'Kibu'
                description = 'Modding library for FabricMC.'
            }
        }
    }
}

// main jar must be built after all the subprojects
subprojects.each {
    if (it.ext.isMc) {
        jar.dependsOn("${it.path}:jar")
    }
}

sourceSets {
    testmod {
        compileClasspath += main.compileClasspath + main.getOutput()
        runtimeClasspath += main.runtimeClasspath + main.getOutput()
    }
}

loom {
    runs {
        named('server') {
            source 'testmod'
        }

        named('client') {
            source 'testmod'
        }
    }
}

dependencies {
    subprojects.each {
        api it
    }
}

// add subprojects as nested jar to the main jar
configurations {
    nestedJars {
        transitive = false
    }
}

dependencies {
    subprojects.each {
        nestedJars project("${it.path}")
    }
}

loom.nestJars(tasks.named("jar"), configurations.nestedJars)

processTestmodResources {
    inputs.property "version", project.version
    inputs.property "loader_version", libs.versions.fabric.loader.get()
    inputs.property "minecraft_compat", project.minecraft_compat

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "loader_version": libs.versions.fabric.loader.get(),
                "minecraft_compat": project.minecraft_compat
    }
}

def checkProjectIsDeployed(Project project, Properties props) {
    def url = "${getDeployUrl(props)}/${project.group.toString().replace('.', '/')}/${project.base.archivesName.get()}/maven-metadata.xml"

    String xml
    try {
        xml = URI.create(url).toURL().text
    } catch (Throwable ignored) {
        return false
    }

    def meta = new XmlSlurper().parseText(xml)
    def versions = meta.versioning.versions.version*.text()

    return versions.contains(project.version)
}

def getDeployUrl(Properties props) {
    Map<String, String> env = System.getenv()

    if (env.containsKey("DEPLOY_URL")) {
        return env.get("DEPLOY_URL")
    } else if (props.containsKey('mavenHost')) {
        return props.getProperty('mavenHost')
    } else {
        return "file:///${rootProject.projectDir}/repo"
    }
}

static def getSubprojectVersion(Project project) {
    def version = project.getProperties()["${project.getName()}-version"]

    if (!version) {
        throw new IllegalStateException("Could not find version for project ${project.getName()}")
    }

    boolean local = System.getProperty("build.local") == "true"
    def suffix = (local ? '+local' : '')

    if (!project.ext.isMc) {
        return version + suffix
    }

    def versionString = version.toString()
    def snapshotSuffix = "-SNAPSHOT"
    def minecraftVersion = project.libs.versions.minecraft.get()

    if (versionString.endsWith(snapshotSuffix)) {
        return versionString.substring(0, versionString.length() - snapshotSuffix.length()) + "+" + minecraftVersion + suffix + snapshotSuffix
    }

    return versionString + "+" + minecraftVersion + suffix
}

static def configureNonLoomProject(Project project) {
    // non-loom subprojects need to have a "namedElements" configuration that provides the project artifacts
    project.configurations {
        namedElements
    }

    // add the project artifacts to the namedElements configuration
    project.apply {
        project.artifacts(artifactHandler -> artifactHandler.add("namedElements", project.getTasks().named("jar")));
    }
}

def moduleDependencies(project, List<String> dependencies) {
    // for each subproject dependency, collect the 'namedElements' configuration
    def deps = dependencies.iterator().collect { project.dependencies.project(path: ":$it") }

    // now add the actual dependency to the project
    project.dependencies {
        deps.each {
            api it
        }
    }
}
