# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.4
yarn_mappings=1.21.4+build.2
loader_version=0.16.9

# Mod Properties
maven_group=work.lclpnet.mods.kibu
archives_base_name=kibu

# Dependencies
fabric_version=0.112.0+1.21.4
translations4j_version=2.11.0

# subproject versions
kibu-fabric-hooks-version=0.5.1
kibu-hooks-version=0.54.2
kibu-command-api-version=0.9.0
kibu-scheduler-api-version=0.9.0
kibu-hook-api-version=1.4.0
kibu-schematic-api-version=0.10.1
kibu-nbt-api-version=0.6.0
kibu-schematic-fabric-version=0.14.0
kibu-title-api-version=0.1.2
kibu-access-lib-version=0.15.0
kibu-inventory-api-version=0.5.2
kibu-translation-api-version=0.21.0
kibu-map-api-version=0.4.1
kibu-behaviour-api-version=0.1.0