plugins {
    id 'java'
}

base {
    archivesName = "kibu-scheduler-api"
}

publishing {
    publications {
        named("mavenJava", MavenPublication) {
            pom {
                name = 'kibu-scheduler-api'
                description = 'Kibu task scheduler API'
            }
        }
    }
}

test {
    useJUnitPlatform()
}