plugins {
    id 'java'
}

base {
    archivesName = "kibu-scheduler-api"
}

publishing {
    publications {
        named("mavenJava", MavenPublication) {
            pom {
                name = 'kibu-scheduler-api'
                description = 'Kibu task scheduler API'
            }
        }
    }
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
}

test {
    useJUnitPlatform()
}