plugins {
    id 'java'
}

base {
    archivesName = "kibu-title-api"
}

publishing {
    publications {
        named("mavenJava", MavenPublication) {
            pom {
                name = 'kibu-title-api'
                description = 'API for sending titles to players'
            }
        }
    }
}