plugins {
    id 'java'
}

base {
    archivesName = "kibu-translation-api"
}

moduleDependencies(project, [
        'kibu-access-lib',
        'kibu-hook-api'
])

publishing {
    publications {
        named("mavenJava", MavenPublication) {
            pom {
                name = 'kibu-translation-api'
                description = 'An API for server-sided translations.'
            }
        }
    }
}

dependencies {
    include(implementation("work.lclpnet:translations4j:${rootProject.translations4j_version}"))
}

test {
    useJUnitPlatform()
}