plugins {
    id 'java'
}

base {
    archivesName = "kibu-fabric-hooks"
}

moduleDependencies(project, [
        'kibu-hook-api'
])

publishing {
    publications {
        named("mavenJava", MavenPublication) {
            pom {
                name = 'kibu-fabric-hooks'
                description = 'A Fabric-API event extension to use them as hooks.'
            }
        }
    }
}