plugins {
    id 'java'
}

base {
    archivesName = "kibu-hook-api"
}

publishing {
    publications {
        named("mavenJava", MavenPublication) {
            pom {
                name = 'kibu-hook-api'
                description = 'Event based hook API with registration/unregistration.'
            }
        }
    }
}

dependencies {
    testCompileOnly 'org.jetbrains:annotations:24.1.0'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
}

test {
    useJUnitPlatform()
}