plugins {
    id 'java'
}

base {
    archivesName = "kibu-assets-api"
}

dependencies {
    implementation(libs.slf4j.api)
    implementation(libs.json)
}

publishing {
    publications {
        named("mavenJava", MavenPublication) {
            pom {
                name = 'kibu-assets-api'
                description = 'A library of for interacting with the game files of Minecraft.'
            }
        }
    }
}