plugins {
    id 'java'
}

base {
    archivesName = "kibu-behaviour-api"
}

publishing {
    publications {
        named("mavenJava", MavenPublication) {
            pom {
                name = 'kibu-behaviour-api'
                description = 'API for customizing vanilla behaviour'
            }
        }
    }
}