plugins {
    id 'java'
}

base {
    archivesName = "kibu-networking-api"
}

moduleDependencies(project, [
        'kibu-hooks'
])

publishing {
    publications {
        named("mavenJava", MavenPublication) {
            pom {
                name = 'kibu-networking-api'
                description = 'Networking API for both client and server'
            }
        }
    }
}