plugins {
    id 'java'
}

base {
    archivesName = "kibu-inventory-api"
}

moduleDependencies(project, [
        'kibu-hook-api',
        'kibu-hooks'
])

publishing {
    publications {
        named("mavenJava", MavenPublication) {
            pom {
                name = 'kibu-inventory-api'
                description = 'An API to easily use inventory screens.'
            }
        }
    }
}