plugins {
    id 'java'
}

archivesBaseName = "kibu-hooks"

moduleDependencies(project, [
        'kibu-hook-api',
        'kibu-access-lib'
])

publishing {
    publications {
        mavenJava(MavenPublication) {
            pom {
                name = 'kibu-hooks'
                description = 'Additional fabric hooks.'
            }
        }
    }
}