plugins {
    id 'java'
}

base {
    archivesName = "kibu-hooks"
}

moduleDependencies(project, [
        'kibu-hook-api'
])

publishing {
    publications {
        named("mavenJava", MavenPublication) {
            pom {
                name = 'kibu-hooks'
                description = 'Additional fabric hooks.'
            }
        }
    }
}