plugins {
    id 'java'
}

base {
    archivesName = "kibu-schematic-fabric"
}

moduleDependencies(project, [
        'kibu-nbt-api',
        'kibu-schematic-api',
        'kibu-access-lib'
])

publishing {
    publications {
        named("mavenJava", MavenPublication) {
            pom {
                name = 'kibu-schematic-fabric'
                description = 'Kibu schematic and NBT API for Fabric'
            }
        }
    }
}

test {
    useJUnitPlatform()
}