plugins {
    id 'java'
}

base {
    archivesName = "kibu-command-api"
}

publishing {
    publications {
        named("mavenJava", MavenPublication) {
            pom {
                name = 'kibu-command-api'
                description = 'API for registering / unregistering commands at runtime'
            }
        }
    }
}

test {
    useJUnitPlatform()
}