plugins {
    id 'java'
}

base {
    archivesName = "kibu-access-lib"
}

publishing {
    publications {
        named("mavenJava", MavenPublication) {
            pom {
                name = 'kibu-access-lib'
                description = 'A library of common accessors that don\'t really fit in other modules.'
            }
        }
    }
}