name: Deployment

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # required to create a release on the repository
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # validate gradle wrapper signature
      - uses: gradle/wrapper-validation-action@v1

      # capture the latest tag
      - name: Set environment variables
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      # Gradle caching and more
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # perform the gradle build
      - name: Execute Gradle Build
        run: ./gradlew build publish github --stacktrace -Porg.gradle.parallel.threads=4
        env:
          CI_VERSION: ${{ steps.vars.outputs.tag }}
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}